INSERT INTO media_videos (
  title,
  description,
  description_short,
  category,
  duration,
  thumbnail_url,
  video_url,
  other_images,
  regie,
  production,
  languages,
  language,
  published_at
)
VALUES
  (
    'Live-Konzert mit...',
    'Das Konzert startet um 13:00 Uhr und du erhältst bereits Zugang um 12:00 Uhr.',
    'Das Konzert startet um 13:00 Uhr und du erhältst bereits Zugang um 12:00 Uhr.',
    'Fokus',
    '03:45',
    '/images/media/konzert-1.jpg',
    '/medien/live-konzert',
    '["/images/media/konzert-1b.jpg"]'::jsonb,
    'Sara Demir',
    'Festival Team',
    ARRAY['Deutsch', 'Kurdisch'],
    'de',
    now() - interval '2 days'
  ),
  (
    'Interview mit...',
    'Schau dir das Interview mit ... an. Du erfährst viel zum Thema Musik und Film.',
    'Schau dir das Interview mit ... an. Du erfährst viel zum Thema Musik und Film.',
    'Featured',
    '02:15',
    '/images/media/interview-1.jpg',
    '/medien/interview',
    '["/images/media/interview-1b.jpg"]'::jsonb,
    'Diljan Aziz',
    'KFF Berlin',
    ARRAY['Deutsch'],
    'de',
    now() - interval '4 days'
  ),
  (
    'Kurdisches Tanzvideo',
    'Hier siehst du einen typischen kurdischen Tanz, wie er bereits seit vielen Jahren ausgetragen wird.',
    'Hier siehst du einen typischen kurdischen Tanz, wie er bereits seit vielen Jahren ausgetragen wird.',
    'Dokumentar',
    '05:20',
    '/images/media/tanz-1.jpg',
    '/medien/tanzvideo',
    '[]'::jsonb,
    'Rojin Dilan',
    'Kulturverein',
    ARRAY['Kurdisch'],
    'de',
    now() - interval '6 days'
  ),
  (
    'Kinderfilm über Musik',
    'Eine kurze Reise durch die Musiktradition für Kinder.',
    'Eine kurze Reise durch die Musiktradition für Kinder.',
    'Kinder',
    '04:10',
    '/images/media/kinder-1.jpg',
    '/medien/kinderfilm',
    '["/images/media/kinder-1b.jpg"]'::jsonb,
    'Berfin Aras',
    'Kinderprogramm',
    ARRAY['Deutsch'],
    'de',
    now() - interval '8 days'
  ),
  (
    'Kurzfilm: Momente',
    'Ein atmosphärischer Kurzfilm über Erinnerungen.',
    'Ein atmosphärischer Kurzfilm über Erinnerungen.',
    'Kurzfilm',
    '01:55',
    '/images/media/kurzfilm-1.jpg',
    '/medien/kurzfilm',
    '["/images/media/kurzfilm-1b.jpg"]'::jsonb,
    'Jiyan Serdar',
    'Filmkollektiv',
    ARRAY['Kurdisch', 'Deutsch'],
    'de',
    now() - interval '9 days'
  );