export const FIELD_CONFIG = {
  form      : ['action','method','classes'],
  input     : ['input_type','name','placeholder','value','required','pattern','minlength','classes'],
  textarea  : ['name','placeholder','value','required','pattern','minlength','classes'],
  select    : ['name','options','required','classes'],
  radio     : ['name','options','required','classes'],
  checkbox  : ['name','value','required','classes'],
  img       : ['src','alt','classes'],
  a         : ['href','content','classes'],
  p         : ['content','classes'],
  h1        : ['content','classes'],
  h2        : ['content','classes'],
  h3        : ['content','classes'],
  button    : ['value','classes'],
  submit    : ['value','classes'],
  ul        : ['classes'],
  ol        : ['classes'],
  li        : ['content','classes'],
  div       : ['content','classes'],
};
